<a href="https://colab.research.google.com/github/fennekoker/Colab/blob/master/Clase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import torch 
import numpy as np
import pandas as pd


#Trabajando con tensores 


---





In [5]:
torch.__version__

'1.5.1+cu101'

In [6]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [7]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[1.6163e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.1634, 0.6114],
        [0.2484, 0.8357]])

In [8]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.8512, 0.3977],
        [0.1256, 0.4173]])

In [12]:
result = tensor_b + tensor_c
result

tensor([[1.0145, 1.0091],
        [0.3740, 1.2531]])

In [14]:
result.shape
reshaped = result.view(1,4)
reshaped

tensor([[1.0145, 1.0091, 0.3740, 1.2531]])

In [17]:
points = torch.tensor([[1.0,4.0],[3.0,9.0]])
print(points)
points[1][1]=7
print(points)
points.storage()

tensor([[1., 4.],
        [3., 9.]])
tensor([[1., 4.],
        [3., 7.]])


 1.0
 4.0
 3.0
 7.0
[torch.FloatStorage of size 4]

In [18]:
points,points.stride()

(tensor([[1., 4.],
         [3., 7.]]), (2, 1))

In [22]:
p_transpuesta = points.t()
p_transpuesta,p_transpuesta.stride()

(tensor([[1., 3.],
         [4., 7.]]), (1, 2))

In [31]:
tensor_x = torch.tensor([1,2,3,4])
tensor_x,torch.unsqueeze(tensor_x,1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [37]:
numpyArray = np.random.randn(2,2)
numpyArray
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[ 0.2715,  0.7981],
        [ 0.2107, -0.9119]], dtype=torch.float64)

#Representar Datos Con Tensores

---



In [39]:
print(from_numpy)
print(torch.mean(from_numpy,dim=0))
print(torch.mean(from_numpy,dim=1))

tensor([[ 0.2715,  0.7981],
        [ 0.2107, -0.9119]], dtype=torch.float64)
tensor([ 0.2411, -0.0569], dtype=torch.float64)
tensor([ 0.5348, -0.3506], dtype=torch.float64)


In [40]:

torch.std(from_numpy,dim=1
          )

tensor([0.3724, 0.7938], dtype=torch.float64)

In [42]:
torch.save(from_numpy,'tensor.t')

In [46]:
load = torch.load('tensor.t')
load

tensor([[ 0.2715,  0.7981],
        [ 0.2107, -0.9119]], dtype=torch.float64)

In [64]:
# Code to read csv file into Colaboratory:!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
import pandas as pd

from oauth2client.client import GoogleCredentials# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

link = '1WMlL-AI9HruuHO3rU7Faa8hti-9TuZec'
#fluff, id = link_pokemonCSV.split('=')print (id) # Verify that you have everything after '='

downloaded = drive.CreateFile({'id':link}) 
downloaded.GetContentFile('england-premier-league-players-2019-to-2020-stats.csv')  
mi_dataframe = pd.read_csv('england-premier-league-players-2019-to-2020-stats.csv')# Dataset is now stored in a Pandas Dataframe
mi_dataframe

full_name  ...  rank_in_club_top_scorer
0                      Kenny Mclean  ...                        9
1                    Kieran Tierney  ...                       21
2                  Stuart Armstrong  ...                        3
3                   Patrick Roberts  ...                       20
4                    James Maddison  ...                        4
..                              ...  ...                      ...
606                Christain Saydee  ...                       -1
607                 Tyrick Mitchell  ...                       14
608                Brandon Pierrick  ...                       13
609  Brandon Leroy Pierrick Keutcha  ...                       26
610                    Bobby Thomas  ...                       -1

[611 rows x 46 columns]

In [65]:
mi_dataframe.columns

Index(['full_name', 'age', 'birthday', 'league', 'season', 'position',
       'Current Club', 'minutes_played_overall', 'minutes_played_home',
       'minutes_played_away', 'nationality', 'appearances_overall',
       'appearances_home', 'appearances_away', 'goals_overall', 'goals_home',
       'goals_away', 'assists_overall', 'assists_home', 'assists_away',
       'penalty_goals', 'penalty_misses', 'clean_sheets_overall',
       'clean_sheets_home', 'clean_sheets_away', 'conceded_overall',
       'conceded_home', 'conceded_away', 'yellow_cards_overall',
       'red_cards_overall', 'goals_involved_per_90_overall',
       'assists_per_90_overall', 'goals_per_90_overall', 'goals_per_90_home',
       'goals_per_90_away', 'min_per_goal_overall', 'conceded_per_90_overall',
       'min_per_conceded_overall', 'min_per_match', 'min_per_card_overall',
       'min_per_assist_overall', 'cards_per_90_overall',
       'rank_in_league_top_attackers', 'rank_in_league_top_midfielders',
       'rank_in

In [95]:
subset = mi_dataframe[['goals_overall','age','appearances_overall','minutes_played_overall','assists_overall']]
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape,players.type()

(torch.Size([611, 5]), 'torch.FloatTensor')

In [67]:
data = players[:,1:]
data,data.shape

(tensor([[2.8000e+01, 3.6000e+01, 2.8760e+03, 1.0000e+00],
         [2.3000e+01, 1.3000e+01, 8.7200e+02, 0.0000e+00],
         [2.8000e+01, 2.8000e+01, 1.5960e+03, 3.0000e+00],
         ...,
         [1.8000e+01, 1.0000e+00, 7.0000e+00, 0.0000e+00],
         [1.8000e+01, 1.0000e+00, 6.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 torch.Size([611, 4]))

In [68]:
target = players[:,0]
target,target.shape

(tensor([ 1.,  0.,  5.,  0.,  6.,  1.,  2., 20.,  0.,  0.,  8.,  0.,  1.,  0.,
          2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,
          0.,  0.,  0., 11.,  0.,  3.,  0.,  2.,  1.,  0., 11.,  0.,  2.,  0.,
          1.,  0.,  0.,  2.,  0.,  0.,  1.,  0.,  0.,  4.,  3.,  5.,  0.,  4.,
          0.,  3.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  2.,
          0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  3.,  1.,  4.,  6.,  0.,  4.,
          4.,  1.,  2.,  0.,  0.,  2.,  1.,  3.,  0.,  0.,  1.,  1.,  2.,  0.,
          2.,  8.,  0., 15.,  2.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
          0., 10., 23.,  2.,  3.,  7.,  0.,  0.,  0.,  5.,  2.,  2.,  0.,  0.,
         10.,  1., 17.,  0.,  4.,  0.,  6.,  2.,  1., 11.,  0.,  2.,  1.,  5.,
          1.,  0.,  0.,  1.,  2.,  2.,  0.,  2.,  0.,  1.,  2.,  0.,  0.,  0.,
          1.,  4.,  1.,  0.,  1.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  4.,
          0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  4.

In [69]:
mean = torch.mean(data,dim=0)
mean

tensor([2.5589e+01, 1.6442e+01, 1.1677e+03, 1.0949e+00])

In [91]:
std = torch.std(data,dim=0)
std

tensor([   5.9445,   12.5426, 1049.2861,    1.9361])

In [96]:
norm = (data-mean)/torch.sqrt(std)
norm

tensor([[  0.9888,   5.5225,  52.7383,  -0.0682],
        [ -1.0620,  -0.9719,  -9.1275,  -0.7869],
        [  0.9888,   3.2636,  13.2232,   1.3692],
        ...,
        [ -3.1127,  -4.3602, -35.8311,  -0.7869],
        [ -3.1127,  -4.3602, -35.8619,  -0.7869],
        [-10.4954,  -4.6426, -36.0472,  -0.7869]])

In [100]:
good = data[torch.ge(target,15)]
average = data[torch.gt(target,7)&torch.lt(target,15)]
notSoGood = data[torch.lt(target,7)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

goodMean,averageMean,notSoGoodMean

(tensor([  27.7273,   31.3636, 2568.7273,    4.4545]),
 tensor([  26.3636,   30.9545, 2231.5454,    4.3182]),
 tensor([2.5531e+01, 1.5503e+01, 1.0925e+03, 8.9005e-01]))

In [104]:
for i, args in enumerate(zip(columns,goodMean,averageMean,notSoGoodMean)) :
  print('{:25}{:6.2f}{:6.2f}{:6.2f}'.format(*args))

age                       27.73 26.36 25.53
appearances_overall       31.36 30.95 15.50
minutes_played_overall   2568.732231.551092.52
assists_overall            4.45  4.32  0.89
